#  Note: This script is tangled from code blocks in the Emacs Org-mode file at
#  https://github.com/jeszyman/exrna/blob/master/exrna.org. Changes
#  made directly to this file will be overwritten upon tangle from Org-mode.


threads: 4
#data_dir: "/mnt/ris/szymanski/exrna_test"
data_dir: "/home/jeszyman/exrna_test"
exrna_script_dir: "workflow/scripts"
container: "${HOME}/sing_containers/rna.1.2.0.sif"
deseq_design: "~ cohort"
#exrna_fasta: "/mnt/ris/szymanski/exrna_test/inputs/chr19.fa"
exrna_fasta: "/home/jeszyman/exrna_test/inputs/chr19.fa"
#exrna_gtf: "/mnt/ris/szymanski/exrna_test/inputs/ENCFF470CZH.gtf"
exrna_gtf: "/home/jeszyman/exrna_test/inputs/ENCFF470CZH.gtf"